import type { Metadata } from 'next';

import StyledComponentsRegistry from '@lib/registry';

import ThemeProvider from '@theme/theme.provider';

import { RootLayoutProps } from '@utils/types.utils';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <StyledComponentsRegistry>
      <ThemeProvider>
        <html lang="pt-br">
          <body>{children}</body>
        </html>
      </ThemeProvider>
    </StyledComponentsRegistry>
  );
}
